# Generated by Django 2.2.10 on 2020-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('area', models.CharField(max_length=200)),
            ],
        ),
    ]
