# Generated by Django 2.2.10 on 2020-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApi', '0002_auto_20200225_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
