# Generated by Django 2.2.10 on 2020-02-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pApi', '0003_auto_20200227_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='date',
            new_name='date1',
        ),
    ]
