# Generated by Django 2.2.10 on 2020-02-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pApi', '0004_auto_20200227_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='date1',
            new_name='date',
        ),
    ]
