# Generated by Django 2.2.10 on 2020-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApi', '0005_auto_20200227_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.DateField(),
        ),
    ]
